import { HeroUIProvider } from "@heroui/react";
import { roboto } from "@/styles/fonts";
import "./globals.css";

export const metadata = {
  title: "Siv",
  description: "Generated by create next app",
  icons: {
    icon: "/favorite.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${roboto.className}`}>
        <HeroUIProvider>
          <div
            className={`dark text-foreground bg-background min-w-[100vw] min-h-[100vh] p-0 m-0`}
          >
            {children}
          </div>
        </HeroUIProvider>
      </body>
    </html>
  );
}
